name: Deploy TinyBench

on:
  push:
    branches:
      - main

    paths:
    - gitops.*
    - '.github/workflows/gitops.yaml'

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO: ghcr.io/retaildevcrews/tinybench

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_ID }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Generate Deployment(s)
      run: |
        git config --global user.email "bartr@microsoft.com"
        git config --global user.name bartr
        git clone https://${{ secrets.GHCR_ID }}:${{ secrets.GHCR_PAT }}@github.com/retaildevcrews/gitops
        cd gitops
        dotnet run -p src
        git pull

    - name: git status
      run: |
        cd gitops
        git status

    - name: git diff
      run: |
        cd gitops
        git diff

    - name: git push
      run: |
        cd gitops
        git pull

        if [[ $(git status -s) ]]; then
          git add .
          git commit -am "gitops TinyBench deployment"
          git push
        fi

